# SQLBoiler Configuration File
# This file tells SQLBoiler how to connect to your database

[psql]
  dbname = "api_db"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = "postgres"
  sslmode = "disable"
  
[sqlboiler]
  no-tests = true